// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoOKHqtC75iCN0VvZFrDNAkJeRUFb17tA',
    appId: '1:674914443498:web:dba3060b7a4f87be2a7793',
    messagingSenderId: '674914443498',
    projectId: 'note-app---fiutter',
    authDomain: 'note-app---fiutter.firebaseapp.com',
    storageBucket: 'note-app---fiutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX9VNQk6rjXRX7LJiYpD2mBWQ-OUysbj8',
    appId: '1:674914443498:android:b2c5123fb2c284242a7793',
    messagingSenderId: '674914443498',
    projectId: 'note-app---fiutter',
    storageBucket: 'note-app---fiutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGRyrEaYEfFIvGbnq3k8Qkrrno5kbCb2Y',
    appId: '1:674914443498:ios:a688f3577a941e302a7793',
    messagingSenderId: '674914443498',
    projectId: 'note-app---fiutter',
    storageBucket: 'note-app---fiutter.appspot.com',
    iosClientId: '674914443498-ib27mc08722o6sk1aom7dvs36i89vqbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGRyrEaYEfFIvGbnq3k8Qkrrno5kbCb2Y',
    appId: '1:674914443498:ios:a688f3577a941e302a7793',
    messagingSenderId: '674914443498',
    projectId: 'note-app---fiutter',
    storageBucket: 'note-app---fiutter.appspot.com',
    iosClientId: '674914443498-ib27mc08722o6sk1aom7dvs36i89vqbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteAppFirebase',
  );
}
